In [71]:
import numpy as np # used for scientific computing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd # used for data analysis and manipulation
import matplotlib.pyplot as plt # used for visualization and plotting
import matplotlib.cm as cm
import scipy as sp
import pprint
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.datasets import load_iris
from sklearn import metrics
import dtreeviz.trees
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from scipy import stats


In [67]:
df = pd.read_csv('inner_data.csv')
column_headers = list(df.columns.values)
data = df.to_numpy()
len(column_headers)
# data

84

In [68]:
data = data[:, 1:]
data = data[:, 1:]
column_headers.pop(0)
column_headers.pop(0)
data.shape
# len(column_headers)

(493, 82)

In [173]:
def provide_best_features(X_train_poly, X_test_poly, y_train, y_test, thresh=0.1):
    # Train the polynomial regression model
    model = LinearRegression()
    print(X_train_poly.shape, y_train.shape)
    model.fit(X_train_poly, y_train)
    # Predict on the testing set
    y_pred = model.predict(X_test_poly)

    # # Calculate mean squared error
    mse = mean_squared_error(y_test, y_pred)
    print("Mean Squared Error:", mse)
    pred_comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
    pred_comparison_df["True/False"] = np.abs(pred_comparison_df["Actual"] - pred_comparison_df["Predicted"]) < thresh        
    print(pred_comparison_df["True/False"].value_counts(normalize=True))
    
    feature_coefficients = np.abs(model.coef_)
    # Get the indices of the top 5 features with the highest coefficients
    top5_indices = np.argsort(feature_coefficients)[-5:]
    # print(top5_indices)
    # Get the names of the top 5 features
    top5_features = poly_names[top5_indices]  # Replace 'feature_names' with the actual names of your features

    # Print the top 5 features
    # print("Top 5 Features:")
    # for feature in top5_features:
    #     print(feature)
    return top5_features, top5_indices

In [135]:
def linear_to_poly_data(X_train, X_test, degree):
    # Create polynomial features
    poly_features = PolynomialFeatures(degree=degree)
    X_train_poly = poly_features.fit_transform(X_train)
    X_test_poly = poly_features.transform(X_test)
    poly_names = poly_features.get_feature_names_out()

    return X_train_poly, X_test_poly
    

In [132]:
def split_data_by_feature(X, y, feature):
    X = np.delete(data, i, axis=1)
    y = data[:, i]

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    return X_train, X_test, y_train, y_test

In [176]:
# run the program
degree=1
best_features = []
for i in range(5):
    print("\nfeature to predict: ",i)
    X_train, X_test, y_train, y_test = split_data_by_feature(X, y, i)
    X_train_poly, X_test_poly = linear_to_poly_data(X_train, X_test, degree)
    best_features.append(provide_best_features(X_train_poly, X_test_poly, y_train, y_test)[1])
    print("predict only with top 5 features:")
    X_train_only_best, X_test_only_best = X_train_poly[:, best_features[i]], X_test_poly[:, best_features[i]]
    provide_best_features(X_train_only_best, X_test_only_best, y_train, y_test)
    print()

print(best_features)
    


feature to predict:  0
(394, 82) (394,)
Mean Squared Error: 0.006284616778804066
True/False
True     0.818182
False    0.181818
Name: proportion, dtype: float64
[60 50 17 80 39]
predict only with top 5 features:
(394, 5) (394,)
Mean Squared Error: 0.010226486361963875
True/False
True     0.747475
False    0.252525
Name: proportion, dtype: float64
[0 3 2 4 1]


feature to predict:  1
(394, 82) (394,)
Mean Squared Error: 0.007866096390748128
True/False
True     0.747475
False    0.252525
Name: proportion, dtype: float64
[43 39 22  2 25]
predict only with top 5 features:
(394, 5) (394,)
Mean Squared Error: 0.02230874036628839
True/False
True     0.565657
False    0.434343
Name: proportion, dtype: float64
[1 0 2 3 4]


feature to predict:  2
(394, 82) (394,)
Mean Squared Error: 0.0041757150479603
True/False
True     0.89899
False    0.10101
Name: proportion, dtype: float64
[17 27 39 30 25]
predict only with top 5 features:
(394, 5) (394,)
Mean Squared Error: 0.006854984930857329
True/Fals

In [166]:
print(best_features)
X_train_only_best, X_test_only_best = X_train_poly[:, best_features[0]], X_test_poly[:, best_features[0]]
print(X_train_only_best.shape, X_test_only_best.shape)
provide_best_features(X_train_only_best, X_test_only_best, y_train, y_test)

[array([60, 50, 17, 80, 39], dtype=int64), array([43, 39, 22,  2, 25], dtype=int64)]
(394, 5) (99, 5)
(394, 5) (394,)
Mean Squared Error: 0.023016675880933684
True/False
False    0.565657
True     0.434343
Name: proportion, dtype: float64
[3 0 1 4 2]
Top 5 Features:
x2
1
x0
x3
x1


(array(['x2', '1', 'x0', 'x3', 'x1'], dtype=object),
 array([3, 0, 1, 4, 2], dtype=int64))